### ISSUE TITLE
window surpport?

### ISSUE THREAD

**Issue by lanybass** [Kagami/go-face#5]
Is it able to be build on windows?
If not,why?

**Comment by Kagami** [comment]
Yes, it's possible since both Go and dlib can be built on Windows. I just don't have that much experience with Windows so can't give you exact instructions yet. Will look into it later.

**Comment by lanybass** [comment]
I've tried to cross compile .exe on ubuntu with MinGW these days,but failed. It's quite complex for me. 
wait for your good news~ thank you

**Comment by Kagami** [comment]
Seems like [vcpkg](https://github.com/Microsoft/vcpkg) can install fresh version of dlib on Windows. I haven't tried but it looks promising.

**Comment by Kagami** [comment]
Tried vcpkg way but failed because it's not easy to make cgo link with MSVC binaries (though some work is going on [here](https://github.com/golang/go/issues/20982)). Also it compiles everything from sources so it took me more than an hour just to build dlib.

Tried msys2 and it worked like a charm, made example work very fast.

Will provide instructions for the msys2 option soon.
